<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE targetDefinitions [ 
	<!ELEMENT targetDefinitions (board)>
	<!ELEMENT board (name, dbgIF+, dbgDEV, mcuId)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT dbgIF (#PCDATA)>
	<!ELEMENT dbgDEV (#PCDATA)>
	<!ELEMENT mcuId (#PCDATA)>
	<!ATTLIST board id CDATA #REQUIRED>
]>

<targetDefinitions>
  <board id="nucleo-f334r8">
    <name>NUCLEO-F334R8</name>
    <dbgIF>SWD</dbgIF>
    <dbgIF>JTAG</dbgIF>
    <dbgDEV>ST-Link</dbgDEV>
    <mcuId>stm32f334r8tx</mcuId>
  </board>
</targetDefinitions>
